cluster.name: es-TaoTuo
node.name: es02
node.master: false
node.data: true
bootstrap.memory_lock: true
network.host: 0.0.0.0
discovery.seed_hosts:
  - es01
  - es04
cluster.initial_master_nodes:
  - es01
  - es04
http.cors.enabled: true
http.cors.allow-origin: "*"
xpack.monitoring.collection.enabled: true